routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){
  return view('test');
});

Route::get('/', function(){
  return view('customer/auth/register');
});

Route::get('home','CustomerController@index')->name('home');

Route::get('payment', function(){
  return view('payments.indexx');
});

Route::get('deconnexion','CustomerController@deco')->name('deconnexion');

Route::put('modifier/{id}','CustomerController@modifier');

Route::get('supprimeraddrese/{lieu}','DeliveryAddressController@supprimer');

Route::get('choix','OrderController@choix');

Route::get('commande/{id}','OrderController@montrer');

Route::get('moi/{id}','CustomerController@profil');

Route::get('vente/{id}','OrderController@vente');

Route::get('lieu/{type}','DeliveryAddressController@details');

Route::get('resultat','ProductController@resultat')->name('resultat');

Route::get('recherche', 'ProductController@recherche')->name('recherche');

Route::get('categorie/{cat}', 'ProductController@cat')->name('categorie');

Auth::routes();

Route::get('prix','ProductController@prix')->name('prix');

Route::get('prixbas','CustomerController@prixbas')->name('prixbas');

Route::get('prixhaut','CustomerController@prixhaut')->name('prixhaut');

Route::get('recent','CustomerController@recent')->name('recent');

Route::get('vieux','CustomerController@vieux')->name('vieux');

Route::get('/admin', 'HomeController@index');

Route::resource('productCategories', 'ProductCategoryController');

Route::resource('productConditions', 'ProductConditionController');

Route::resource('countries', 'CountryController');

Route::resource('currencies', 'CurrencyController');

Route::resource('customers', 'CustomerController');

Route::resource('deliveryAddresses', 'DeliveryAddressController');

Route::resource('products', 'ProductController');

Route::resource('photos', 'PhotoController');

Route::resource('productMedia', 'ProductMediaController');

Route::resource('productMediaTypes', 'ProductMediaTypeController');

Route::resource('flashSellings', 'FlashSellingController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('orders', 'OrderController');

Route::resource('orderHistories', 'OrderHistoryController');

Route::resource('userDefaultDeliveryServices', 'UserDefaultDeliveryServiceController');

Route::resource('deliveryServices', 'DeliveryServiceController');

Route::resource('orderAssignments', 'OrderAssignmentController');

Route::resource('orderDeliveries', 'OrderDeliveryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('invoices', 'InvoiceController');

Route::resource('favoriteProducts', 'FavoriteProductController');

Route::resource('follows', 'FollowController');

Route::resource('customerNotifications', 'CustomerNotificationController');

Route::resource('customerDevices', 'CustomerDeviceController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('coupons', 'CouponController');

Route::resource('conversations', 'ConversationController');

Route::resource('messages', 'MessageController');

Route::resource('notificationTypes', 'NotificationTypeController');

Route::resource('sponsoringTypes', 'SponsoringTypeController');

Route::resource('sponsorings', 'SponsoringController');

Route::resource('payments', 'PaymentController');

Route::resource('paymentSources', 'PaymentSourceController');

Route::resource('contacts', 'ContactController');

Route::resource('contactInvitations', 'ContactInvitationController');

Route::resource('walletTokens', 'WalletTokenController');

Route::resource('tokenTransactions', 'TokenTransactionController');

Route::resource('evaluateSellers', 'EvaluateSellerController');

Route::resource('customerIssues', 'CustomerIssueController');

Route::resource('productAudiences', 'ProductAudienceController');
Route::post('notify', 'InvoiceController@notify');
Route::get('cancel/{transactionId}', 'InvoiceController@cancelTransaction');

Route::resource('users', 'UserController');
Route::group(['prefix' => 'customer'], function () {
  Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'CustomerAuth\LoginController@login');
  Route::post('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'CustomerAuth\RegisterController@register');

  Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

app/Models/ProductCondition.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="ProductCondition",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="slug",
 *          description="slug",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="language",
 *          description="language",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class ProductCondition extends Model
{
    use SoftDeletes;

    public $table = 'product_conditions';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'slug',
        'language'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'slug' => 'string',
        'language' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/ProductConditionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductConditionRequest;
use App\Http\Requests\UpdateProductConditionRequest;
use App\Repositories\ProductConditionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class ProductConditionController extends AppBaseController
{
    /** @var  ProductConditionRepository */
    private $productConditionRepository;

    public function __construct(ProductConditionRepository $productConditionRepo)
    {
        $this->productConditionRepository = $productConditionRepo;
    }

    /**
     * Display a listing of the ProductCondition.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $productConditions = $this->productConditionRepository->all();

        return view('product_conditions.index')
            ->with('productConditions', $productConditions);
    }

    /**
     * Show the form for creating a new ProductCondition.
     *
     * @return Response
     */
    public function create()
    {
        return view('product_conditions.create');
    }

    /**
     * Store a newly created ProductCondition in storage.
     *
     * @param CreateProductConditionRequest $request
     *
     * @return Response
     */
    public function store(CreateProductConditionRequest $request)
    {
        $input = $request->all();

        $productCondition = $this->productConditionRepository->create($input);

        Flash::success('Product Condition saved successfully.');

        return redirect(route('productConditions.index'));
    }

    /**
     * Display the specified ProductCondition.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $productCondition = $this->productConditionRepository->find($id);

        if (empty($productCondition)) {
            Flash::error('Product Condition not found');

            return redirect(route('productConditions.index'));
        }

        return view('product_conditions.show')->with('productCondition', $productCondition);
    }

    /**
     * Show the form for editing the specified ProductCondition.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $productCondition = $this->productConditionRepository->find($id);

        if (empty($productCondition)) {
            Flash::error('Product Condition not found');

            return redirect(route('productConditions.index'));
        }

        return view('product_conditions.edit')->with('productCondition', $productCondition);
    }

    /**
     * Update the specified ProductCondition in storage.
     *
     * @param int $id
     * @param UpdateProductConditionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductConditionRequest $request)
    {
        $productCondition = $this->productConditionRepository->find($id);

        if (empty($productCondition)) {
            Flash::error('Product Condition not found');

            return redirect(route('productConditions.index'));
        }

        $productCondition = $this->productConditionRepository->update($request->all(), $id);

        Flash::success('Product Condition updated successfully.');

        return redirect(route('productConditions.index'));
    }

    /**
     * Remove the specified ProductCondition from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $productCondition = $this->productConditionRepository->find($id);

        if (empty($productCondition)) {
            Flash::error('Product Condition not found');

            return redirect(route('productConditions.index'));
        }

        $this->productConditionRepository->delete($id);

        Flash::success('Product Condition deleted successfully.');

        return redirect(route('productConditions.index'));
    }
}

resources/views/product_conditions/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('productConditions.index') !!}">Product Condition</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Product Condition</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'productConditions.store']) !!}

                                   @include('product_conditions.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/product_conditions/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('productConditions.index') !!}">Product Condition</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Product Condition</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($productCondition, ['route' => ['productConditions.update', $productCondition->id], 'method' => 'patch']) !!}

                              @include('product_conditions.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/product_conditions/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('slug', 'Slug:') !!}
    {!! Form::text('slug', null, ['class' => 'form-control']) !!}
</div>

<!-- Language Field -->
<div class="form-group col-sm-6">
    {!! Form::label('language', 'Language:') !!}
    {!! Form::text('language', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('productConditions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/product_conditions/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Product Conditions</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             ProductConditions
                             <a class="pull-right" href="{!! route('productConditions.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('product_conditions.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/product_conditions/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('productConditions.index') !!}">Product Condition</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('productConditions.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('product_conditions.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/product_conditions/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $productCondition->name !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{!! $productCondition->slug !!}</p>
</div>

<!-- Language Field -->
<div class="form-group">
    {!! Form::label('language', 'Language:') !!}
    <p>{!! $productCondition->language !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $productCondition->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $productCondition->updated_at !!}</p>
</div>

resources/views/product_conditions/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="productConditions-table">
        <thead>
            <th>Name</th>
            <th>Name EN</th>
            <th>Slug</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($productConditions as $productCondition)
            <tr>
            <td>{!! $productCondition->name !!}</td>
            <td>{!! $productCondition->name_en !!}</td>
            <td>{!! $productCondition->slug !!}</td>
                <td>
                    {!! Form::open(['route' => ['productConditions.destroy', $productCondition->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('productConditions.show', [$productCondition->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('productConditions.edit', [$productCondition->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>