routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){
  return view('test');
});

Route::get('/', function(){
  return view('customer/auth/register');
});

Route::get('home','CustomerController@index')->name('home');

Route::get('payment', function(){
  return view('payments.indexx');
});

Route::get('deconnexion','CustomerController@deco')->name('deconnexion');

Route::put('modifier/{id}','CustomerController@modifier');

Route::get('supprimeraddrese/{lieu}','DeliveryAddressController@supprimer');

Route::get('choix','OrderController@choix');

Route::get('commande/{id}','OrderController@montrer');

Route::get('moi/{id}','CustomerController@profil');

Route::get('vente/{id}','OrderController@vente');

Route::get('lieu/{type}','DeliveryAddressController@details');

Route::get('resultat','ProductController@resultat')->name('resultat');

Route::get('recherche', 'ProductController@recherche')->name('recherche');

Route::get('categorie/{cat}', 'ProductController@cat')->name('categorie');

Auth::routes();

Route::get('prix','ProductController@prix')->name('prix');

Route::get('prixbas','CustomerController@prixbas')->name('prixbas');

Route::get('prixhaut','CustomerController@prixhaut')->name('prixhaut');

Route::get('recent','CustomerController@recent')->name('recent');

Route::get('vieux','CustomerController@vieux')->name('vieux');

Route::get('/admin', 'HomeController@index');

Route::resource('productCategories', 'ProductCategoryController');

Route::resource('productConditions', 'ProductConditionController');

Route::resource('countries', 'CountryController');

Route::resource('currencies', 'CurrencyController');

Route::resource('customers', 'CustomerController');

Route::resource('deliveryAddresses', 'DeliveryAddressController');

Route::resource('products', 'ProductController');

Route::resource('photos', 'PhotoController');

Route::resource('productMedia', 'ProductMediaController');

Route::resource('productMediaTypes', 'ProductMediaTypeController');

Route::resource('flashSellings', 'FlashSellingController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('orders', 'OrderController');

Route::resource('orderHistories', 'OrderHistoryController');

Route::resource('userDefaultDeliveryServices', 'UserDefaultDeliveryServiceController');

Route::resource('deliveryServices', 'DeliveryServiceController');

Route::resource('orderAssignments', 'OrderAssignmentController');

Route::resource('orderDeliveries', 'OrderDeliveryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('invoices', 'InvoiceController');

Route::resource('favoriteProducts', 'FavoriteProductController');

Route::resource('follows', 'FollowController');

Route::resource('customerNotifications', 'CustomerNotificationController');

Route::resource('customerDevices', 'CustomerDeviceController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('coupons', 'CouponController');

Route::resource('conversations', 'ConversationController');

Route::resource('messages', 'MessageController');

Route::resource('notificationTypes', 'NotificationTypeController');

Route::resource('sponsoringTypes', 'SponsoringTypeController');

Route::resource('sponsorings', 'SponsoringController');

Route::resource('payments', 'PaymentController');

Route::resource('paymentSources', 'PaymentSourceController');

Route::resource('contacts', 'ContactController');

Route::resource('contactInvitations', 'ContactInvitationController');

Route::resource('walletTokens', 'WalletTokenController');

Route::resource('tokenTransactions', 'TokenTransactionController');

Route::resource('evaluateSellers', 'EvaluateSellerController');

Route::resource('customerIssues', 'CustomerIssueController');

Route::resource('productAudiences', 'ProductAudienceController');
Route::post('notify', 'InvoiceController@notify');
Route::get('cancel/{transactionId}', 'InvoiceController@cancelTransaction');

Route::resource('users', 'UserController');
Route::group(['prefix' => 'customer'], function () {
  Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'CustomerAuth\LoginController@login');
  Route::post('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'CustomerAuth\RegisterController@register');

  Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

app/Models/DeliveryService.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="DeliveryService",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="smartlivraison_username",
 *          description="smartlivraison_username",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="logo",
 *          description="logo",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="delivery_level",
 *          description="delivery_level",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class DeliveryService extends Model
{
    use SoftDeletes;

    public $table = 'delivery_services';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'smartlivraison_username',
        'email',
        'logo',
        'delivery_level',
        'phone'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'smartlivraison_username' => 'string',
        'email' => 'string',
        'logo' => 'string',
        'delivery_level' => 'string',
        'phone' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/DeliveryServiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateDeliveryServiceRequest;
use App\Http\Requests\UpdateDeliveryServiceRequest;
use App\Repositories\DeliveryServiceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class DeliveryServiceController extends AppBaseController
{
    /** @var  DeliveryServiceRepository */
    private $deliveryServiceRepository;

    public function __construct(DeliveryServiceRepository $deliveryServiceRepo)
    {
        $this->deliveryServiceRepository = $deliveryServiceRepo;
    }

    /**
     * Display a listing of the DeliveryService.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $deliveryServices = $this->deliveryServiceRepository->all();

        return view('delivery_services.index')
            ->with('deliveryServices', $deliveryServices);
    }

    /**
     * Show the form for creating a new DeliveryService.
     *
     * @return Response
     */
    public function create()
    {
        return view('delivery_services.create');
    }

    /**
     * Store a newly created DeliveryService in storage.
     *
     * @param CreateDeliveryServiceRequest $request
     *
     * @return Response
     */
    public function store(CreateDeliveryServiceRequest $request)
    {
        $input = $request->all();

        $deliveryService = $this->deliveryServiceRepository->create($input);

        Flash::success('Delivery Service saved successfully.');

        return redirect(route('deliveryServices.index'));
    }

    /**
     * Display the specified DeliveryService.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $deliveryService = $this->deliveryServiceRepository->find($id);

        if (empty($deliveryService)) {
            Flash::error('Delivery Service not found');

            return redirect(route('deliveryServices.index'));
        }

        return view('delivery_services.show')->with('deliveryService', $deliveryService);
    }

    /**
     * Show the form for editing the specified DeliveryService.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $deliveryService = $this->deliveryServiceRepository->find($id);

        if (empty($deliveryService)) {
            Flash::error('Delivery Service not found');

            return redirect(route('deliveryServices.index'));
        }

        return view('delivery_services.edit')->with('deliveryService', $deliveryService);
    }

    /**
     * Update the specified DeliveryService in storage.
     *
     * @param int $id
     * @param UpdateDeliveryServiceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDeliveryServiceRequest $request)
    {
        $deliveryService = $this->deliveryServiceRepository->find($id);

        if (empty($deliveryService)) {
            Flash::error('Delivery Service not found');

            return redirect(route('deliveryServices.index'));
        }

        $deliveryService = $this->deliveryServiceRepository->update($request->all(), $id);

        Flash::success('Delivery Service updated successfully.');

        return redirect(route('deliveryServices.index'));
    }

    /**
     * Remove the specified DeliveryService from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $deliveryService = $this->deliveryServiceRepository->find($id);

        if (empty($deliveryService)) {
            Flash::error('Delivery Service not found');

            return redirect(route('deliveryServices.index'));
        }

        $this->deliveryServiceRepository->delete($id);

        Flash::success('Delivery Service deleted successfully.');

        return redirect(route('deliveryServices.index'));
    }
}

resources/views/delivery_services/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('deliveryServices.index') !!}">Delivery Service</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Delivery Service</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'deliveryServices.store']) !!}

                                   @include('delivery_services.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/delivery_services/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('deliveryServices.index') !!}">Delivery Service</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Delivery Service</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($deliveryService, ['route' => ['deliveryServices.update', $deliveryService->id], 'method' => 'patch']) !!}

                              @include('delivery_services.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/delivery_services/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Smartlivraison Username Field -->
<div class="form-group col-sm-6">
    {!! Form::label('smartlivraison_username', 'Smartlivraison Username:') !!}
    {!! Form::text('smartlivraison_username', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Logo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('logo', 'Logo:') !!}
    {!! Form::text('logo', null, ['class' => 'form-control']) !!}
</div>

<!-- Delivery Level Field -->
<div class="form-group col-sm-6">
    {!! Form::label('delivery_level', 'Delivery Level:') !!}
    {!! Form::text('delivery_level', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('deliveryServices.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/delivery_services/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Delivery Services</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             DeliveryServices
                             <a class="pull-right" href="{!! route('deliveryServices.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('delivery_services.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/delivery_services/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('deliveryServices.index') !!}">Delivery Service</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('deliveryServices.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('delivery_services.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/delivery_services/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $deliveryService->name !!}</p>
</div>

<!-- Smartlivraison Username Field -->
<div class="form-group">
    {!! Form::label('smartlivraison_username', 'Smartlivraison Username:') !!}
    <p>{!! $deliveryService->smartlivraison_username !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $deliveryService->email !!}</p>
</div>

<!-- Logo Field -->
<div class="form-group">
    {!! Form::label('logo', 'Logo:') !!}
    <p>{!! $deliveryService->logo !!}</p>
</div>

<!-- Delivery Level Field -->
<div class="form-group">
    {!! Form::label('delivery_level', 'Delivery Level:') !!}
    <p>{!! $deliveryService->delivery_level !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $deliveryService->phone !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $deliveryService->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $deliveryService->updated_at !!}</p>
</div>

resources/views/delivery_services/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="deliveryServices-table">
        <thead>
            <th>Name</th>
        <th>Smartlivraison Username</th>
        <th>Email</th>
        <th>Logo</th>
        <th>Delivery Level</th>
        <th>Phone</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($deliveryServices as $deliveryService)
            <tr>
                <td>{!! $deliveryService->name !!}</td>
            <td>{!! $deliveryService->smartlivraison_username !!}</td>
            <td>{!! $deliveryService->email !!}</td>
            <td>{!! $deliveryService->logo !!}</td>
            <td>{!! $deliveryService->delivery_level !!}</td>
            <td>{!! $deliveryService->phone !!}</td>
                <td>
                    {!! Form::open(['route' => ['deliveryServices.destroy', $deliveryService->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('deliveryServices.show', [$deliveryService->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('deliveryServices.edit', [$deliveryService->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>