routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){
  return view('test');
});

Route::get('/', function(){
  return view('customer/auth/register');
});

Route::get('home','CustomerController@index')->name('home');

Route::get('payment', function(){
  return view('payments.indexx');
});

Route::get('deconnexion','CustomerController@deco')->name('deconnexion');

Route::put('modifier/{id}','CustomerController@modifier');

Route::get('supprimeraddrese/{lieu}','DeliveryAddressController@supprimer');

Route::get('choix','OrderController@choix');

Route::get('commande/{id}','OrderController@montrer');

Route::get('moi/{id}','CustomerController@profil');

Route::get('vente/{id}','OrderController@vente');

Route::get('lieu/{type}','DeliveryAddressController@details');

Route::get('resultat','ProductController@resultat')->name('resultat');

Route::get('recherche', 'ProductController@recherche')->name('recherche');

Route::get('categorie/{cat}', 'ProductController@cat')->name('categorie');

Auth::routes();

Route::get('prix','ProductController@prix')->name('prix');

Route::get('prixbas','CustomerController@prixbas')->name('prixbas');

Route::get('prixhaut','CustomerController@prixhaut')->name('prixhaut');

Route::get('recent','CustomerController@recent')->name('recent');

Route::get('vieux','CustomerController@vieux')->name('vieux');

Route::get('/admin', 'HomeController@index');

Route::resource('productCategories', 'ProductCategoryController');

Route::resource('productConditions', 'ProductConditionController');

Route::resource('countries', 'CountryController');

Route::resource('currencies', 'CurrencyController');

Route::resource('customers', 'CustomerController');

Route::resource('deliveryAddresses', 'DeliveryAddressController');

Route::resource('products', 'ProductController');

Route::resource('photos', 'PhotoController');

Route::resource('productMedia', 'ProductMediaController');

Route::resource('productMediaTypes', 'ProductMediaTypeController');

Route::resource('flashSellings', 'FlashSellingController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('orders', 'OrderController');

Route::resource('orderHistories', 'OrderHistoryController');

Route::resource('userDefaultDeliveryServices', 'UserDefaultDeliveryServiceController');

Route::resource('deliveryServices', 'DeliveryServiceController');

Route::resource('orderAssignments', 'OrderAssignmentController');

Route::resource('orderDeliveries', 'OrderDeliveryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('invoices', 'InvoiceController');

Route::resource('favoriteProducts', 'FavoriteProductController');

Route::resource('follows', 'FollowController');

Route::resource('customerNotifications', 'CustomerNotificationController');

Route::resource('customerDevices', 'CustomerDeviceController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('coupons', 'CouponController');

Route::resource('conversations', 'ConversationController');

Route::resource('messages', 'MessageController');

Route::resource('notificationTypes', 'NotificationTypeController');

Route::resource('sponsoringTypes', 'SponsoringTypeController');

Route::resource('sponsorings', 'SponsoringController');

Route::resource('payments', 'PaymentController');

Route::resource('paymentSources', 'PaymentSourceController');

Route::resource('contacts', 'ContactController');

Route::resource('contactInvitations', 'ContactInvitationController');

Route::resource('walletTokens', 'WalletTokenController');

Route::resource('tokenTransactions', 'TokenTransactionController');

Route::resource('evaluateSellers', 'EvaluateSellerController');

Route::resource('customerIssues', 'CustomerIssueController');

Route::resource('productAudiences', 'ProductAudienceController');
Route::post('notify', 'InvoiceController@notify');
Route::get('cancel/{transactionId}', 'InvoiceController@cancelTransaction');

Route::resource('users', 'UserController');
Route::group(['prefix' => 'customer'], function () {
  Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'CustomerAuth\LoginController@login');
  Route::post('/logout', 'CustomerAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'CustomerAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'CustomerAuth\RegisterController@register');

  Route::post('/password/email', 'CustomerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'CustomerAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'CustomerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'CustomerAuth\ResetPasswordController@showResetForm');
});

app/Models/OrderItem.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Order;
use App\Models\Product;

/**
 * @SWG\Definition(
 *      definition="OrderItem",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="order_id",
 *          description="order_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="meta_data",
 *          description="meta_data",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="quantity",
 *          description="quantity",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="quantity_unit",
 *          description="quantity_unit",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="unit_price",
 *          description="unit_price",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="currency_code",
 *          description="currency_code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="total_amount",
 *          description="total_amount",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class OrderItem extends Model
{
    use SoftDeletes;

    public $table = 'order_items';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'order_id',
        'meta_data_id',
        'meta_data',
        'quantity',
        'quantity_unit',
        'unit_price',
        'currency_code',
        'total_amount'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'order_id' => 'integer',
        'meta_data_id' => 'integer',
        'meta_data' => 'string',
        'quantity' => 'integer',
        'quantity_unit' => 'string',
        'unit_price' => 'string',
        'currency_code' => 'string',
        'total_amount' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function order(){
        return $this->belongsTo('App\Models\Order');
    }

    public function product(){
        return $this->belongsTo('App\Models\Product','meta_data_id');
    }
}

app/Http/Controllers/OrderItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrderItemRequest;
use App\Http\Requests\UpdateOrderItemRequest;
use App\Repositories\OrderItemRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class OrderItemController extends AppBaseController
{
    /** @var  OrderItemRepository */
    private $orderItemRepository;

    public function __construct(OrderItemRepository $orderItemRepo)
    {
        $this->orderItemRepository = $orderItemRepo;
    }

    /**
     * Display a listing of the OrderItem.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $orderItems = $this->orderItemRepository->all();

        return view('order_items.index')
            ->with('orderItems', $orderItems);
    }

    /**
     * Show the form for creating a new OrderItem.
     *
     * @return Response
     */
    public function create()
    {
        return view('order_items.create');
    }

    /**
     * Store a newly created OrderItem in storage.
     *
     * @param CreateOrderItemRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderItemRequest $request)
    {
        $input = $request->all();

        $orderItem = $this->orderItemRepository->create($input);

        Flash::success('Order Item saved successfully.');

        return redirect(route('orderItems.index'));
    }

    /**
     * Display the specified OrderItem.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        return view('order_items.show')->with('orderItem', $orderItem);
    }

    /**
     * Show the form for editing the specified OrderItem.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        return view('order_items.edit')->with('orderItem', $orderItem);
    }

    /**
     * Update the specified OrderItem in storage.
     *
     * @param int $id
     * @param UpdateOrderItemRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderItemRequest $request)
    {
        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        $orderItem = $this->orderItemRepository->update($request->all(), $id);

        Flash::success('Order Item updated successfully.');

        return redirect(route('orderItems.index'));
    }

    /**
     * Remove the specified OrderItem from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        $this->orderItemRepository->delete($id);

        Flash::success('Order Item deleted successfully.');

        return redirect(route('orderItems.index'));
    }
}

resources/views/order_items/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('orderItems.index') !!}">Order Item</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Order Item</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'orderItems.store']) !!}

                                   @include('order_items.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/order_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('orderItems.index') !!}">Order Item</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Order Item</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($orderItem, ['route' => ['orderItems.update', $orderItem->id], 'method' => 'patch']) !!}

                              @include('order_items.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/order_items/fields.blade.php
<!-- Order Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order_id', 'Order Id:') !!}
    {!! Form::text('order_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Meta Data Field -->
<div class="form-group col-sm-6">
    {!! Form::label('meta_data', 'Meta Data:') !!}
    {!! Form::text('meta_data', null, ['class' => 'form-control']) !!}
</div>

<!-- Quantity Field -->
<div class="form-group col-sm-6">
    {!! Form::label('quantity', 'Quantity:') !!}
    {!! Form::text('quantity', null, ['class' => 'form-control']) !!}
</div>

<!-- Quantity Unit Field -->
<div class="form-group col-sm-6">
    {!! Form::label('quantity_unit', 'Quantity Unit:') !!}
    {!! Form::text('quantity_unit', null, ['class' => 'form-control']) !!}
</div>

<!-- Unit Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('unit_price', 'Unit Price:') !!}
    {!! Form::text('unit_price', null, ['class' => 'form-control']) !!}
</div>

<!-- Currency Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('currency_code', 'Currency Code:') !!}
    {!! Form::text('currency_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Total Amount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_amount', 'Total Amount:') !!}
    {!! Form::text('total_amount', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('orderItems.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/order_items/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Order Items</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             OrderItems
                             <a class="pull-right" href="{!! route('orderItems.create') !!}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('order_items.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/order_items/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{!! route('orderItems.index') !!}">Order Item</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{!! route('orderItems.index') !!}" class="btn btn-ghost-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('order_items.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/order_items/show_fields.blade.php
<!-- Order Id Field -->
<div class="form-group">
    {!! Form::label('order_id', 'Order Id:') !!}
    <p>{!! $orderItem->order_id !!}</p>
</div>

<!-- Meta Data Field -->
<div class="form-group">
    {!! Form::label('meta_data', 'Meta Data:') !!}
    <p>{!! $orderItem->meta_data !!}</p>
</div>

<!-- Quantity Field -->
<div class="form-group">
    {!! Form::label('quantity', 'Quantity:') !!}
    <p>{!! $orderItem->quantity !!}</p>
</div>

<!-- Quantity Unit Field -->
<div class="form-group">
    {!! Form::label('quantity_unit', 'Quantity Unit:') !!}
    <p>{!! $orderItem->quantity_unit !!}</p>
</div>

<!-- Unit Price Field -->
<div class="form-group">
    {!! Form::label('unit_price', 'Unit Price:') !!}
    <p>{!! $orderItem->unit_price !!}</p>
</div>

<!-- Currency Code Field -->
<div class="form-group">
    {!! Form::label('currency_code', 'Currency Code:') !!}
    <p>{!! $orderItem->currency_code !!}</p>
</div>

<!-- Total Amount Field -->
<div class="form-group">
    {!! Form::label('total_amount', 'Total Amount:') !!}
    <p>{!! $orderItem->total_amount !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $orderItem->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $orderItem->updated_at !!}</p>
</div>

resources/views/order_items/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="orderItems-table">
        <thead>
            <th>Order Id</th>
        <th>Meta Data</th>
        <th>Quantity</th>
        <th>Quantity Unit</th>
        <th>Unit Price</th>
        <th>Currency Code</th>
        <th>Total Amount</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($orderItems as $orderItem)
            <tr>
                <td>{!! $orderItem->order_id !!}</td>
            <td>{!! $orderItem->meta_data !!}</td>
            <td>{!! $orderItem->quantity !!}</td>
            <td>{!! $orderItem->quantity_unit !!}</td>
            <td>{!! $orderItem->unit_price !!}</td>
            <td>{!! $orderItem->currency_code !!}</td>
            <td>{!! $orderItem->total_amount !!}</td>
                <td>
                    {!! Form::open(['route' => ['orderItems.destroy', $orderItem->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('orderItems.show', [$orderItem->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('orderItems.edit', [$orderItem->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>